### ISSUE TITLE
What does each cubemap format means

### ISSUE THREAD

**Issue by BlueHorn07** [sunset1995/py360convert#1]
In the README.md, c2e categorize the input cubemap's format, 'dice' (default), 'horizon', 'dict' and  'list'. But, there's no further explain about that format because i guess there's no formal sentence for cubemap format.

I searched about cubemap formap and there's some shape of cubemap.
![cubemap_format](https://docs.unity3d.com/uploads/Textures/CubeLayout6Faces.png)

So, if anyone have time to add the more precise explain about format. Please add it :)
Thank you for reading.

**Comment by sunset1995** [comment]
I update README [a little bit](https://github.com/sunset1995/py360convert#c2ecubemap-h-w-cube_formatdice).
Hope it helps you better understanding the format in this repo.
PRs are welcomed if you can help me support more cube formats. (The initial format in this repo is just for my implementation convenient)

**Comment by Boscop** [comment]
@sunset1995 Is it possible to generate 6 different image files for the cubemap faces? :)
