### ISSUE TITLE
Bug in c2e

### ISSUE THREAD

**Issue by muhammad-tayyab** [sunset1995/py360convert#10]
I am using p360convert with python 3.7.8. I tried e2c and it worked as expected but I am having issue in c2e. I used the example, but same issue appeared. Am I doing it wrong or is this a bug?

`cube_dice = np.array(Image.open('assert/example_e2c.png'))`
`Image.fromarray(py360convert.c2e(cube_dice,400,800), 'RGB').show()`

![image](https://user-images.githubusercontent.com/11335086/97133687-c9489b00-1785-11eb-9fe1-5a49e79c67ea.png)

**Comment by fuyb1992** [comment]
`Image.fromarray(py360convert.c2e(cube_dice,400,800).astype(np.uint8)).show()` may works

**Comment by BrianPugh** [comment]
On `master`, functions like `py360convert.c2e` now correctly return the same dtype as the input array, so the `astype(np.uint8)` is no longer needed. This will be included in the upcoming release (early January).
