### ISSUE TITLE
a big bug in c2e

### ISSUE THREAD

**Issue by dlutwuwei** [sunset1995/py360convert#11]
The list of equirectangulars generated by c2e is not right, look the picture：
![Lark20201112-170458](https://user-images.githubusercontent.com/3362483/98918986-40fa2200-2509-11eb-9c3b-6dbe87a21a2e.jpeg)

the right, back and up picture is reversed, use an another tool, we got a right list pictures.

![Lark20201112-170653](https://user-images.githubusercontent.com/3362483/98919206-8159a000-2509-11eb-8e83-30d041208495.png)

**Comment by Boscop** [comment]
@dlutwuwei Which tool would you recommend?

**Comment by lavalamp3774** [comment]
@Boscop You can use a simple numpy function to fix this, here's what I'm doing:

write_img('front', faces[0])
write_img('right', np.flip(faces[1], 1))
write_img('back', np.flip(faces[2], 1))
write_img('left', faces[3])
write_img('up', np.flip(faces[4], 0))
write_img('down', faces[5])

**Comment by BrianPugh** [comment]
addressed in #28
