### ISSUE TITLE
New PyPi Release

### ISSUE THREAD

**Issue by BrianPugh** [sunset1995/py360convert#16]
Thanks for your library @sunset1995 ! I was wondering if you could tag a new release for pypi; seems like some bugs have been fixed since the initial release. Thanks!

**Comment by johansvenson** [comment]
please arrange a new pypi release

**Comment by rejexx** [comment]
@sunset1995 Any udpates on __"A new library including more fuctionality for 360 is under contruction by my colleague. This repo will be depreciated then.__"?  Or allowing someone to maintain this very useful repo by accepting some of the pull requests?

**Comment by BrianPugh** [comment]
Update: I just got added as a maintainer to this repo; I'll be merging in bugfixes and cutting a release in early January (just to make sure noone with unpinned dependencies gets caught off guard right before the holidays)

**Comment by ProGamerGov** [comment]
Its nice to see someone working on this library again!

I have been working on a PyTorch version of this library, and it will hopefully be ready to share soon. That should hopefully make it easier for those with machine learning and AI related use cases.

**Comment by ProGamerGov** [comment]
Its nice to see someone working on this library again! I've also been coincidentally working on a PyTorch version of this library, to make it easier for AI researchers to use this project with their AI related research.

My PyTorch version of this library can be found here: https://github.com/ProGamerGov/pytorch360convert

**Comment by BrianPugh** [comment]
I think this repo is in a pretty good shape now; please provide feedback! Planned tagged release v1.0.0 will happen around Jan 2.

**Comment by BrianPugh** [comment]
closed in favor of #32
