### ISSUE TITLE
recommended reading materials

### ISSUE THREAD

**Issue by yinlingluo** [sunset1995/py360convert#2]
Thank you for this great contribution!
Yet, I am wondering where we could find are some reading materials that might help us understand the theory foundation behind the implementations.
Any recommendation would be appreciated!

**Comment by ThomasParistech** [comment]
Hi!
I just wrote a Medium article about the theory behind these conversions. Hope it helps :)
https://medium.com/check-visit-computer-vision/understanding-360-images-8e0fcf0ee861
