### ISSUE TITLE
Tiny issue with 'dict' cube_format

### ISSUE THREAD

**Issue by Ephraim-Bryski** [sunset1995/py360convert#22]
I came across a tiny mistake in `c2e` conversion with the 'dict' `cube_format` and I wanted to share in case it would be helpful (I could make a pull request instead if desired).

In `cube_dict2h()` in `utils.py`, I think the variables in the assertion should be `face_k`  instead of `k`:
```python
def cube_dict2h(cube_dict, face_k=['F', 'R', 'B', 'L', 'U', 'D']):
    assert len(face_k) == 6
    # instead of:
    # assert len(k) == 6
    return cube_list2h([cube_dict[k] for k in face_k])
```

I also came across something that might be a mistake. In `equirect_facetype()` also in `utils.py`, it uses `np.bool`, which doesn't seem to exist. Instead I specified the datatype as a boolean:
```python 
def equirect_facetype(h, w):
    '''
    0F 1R 2B 3L 4U 5D
    '''
    tp = np.roll(np.arange(4).repeat(w // 4)[None, :].repeat(h, 0), 3 * w // 8, 1)

    # specify the dtype as boolean:
    mask = np.zeros((h, w // 4), dtype='?')
    # this gives me an error (it doesn't look like np.bool exists):
    # mask = np.zeros((h, w // 4), np.bool)
    idx = np.linspace(-np.pi, np.pi, w // 4) / 4
    idx = h // 2 - np.round(np.arctan(np.cos(idx)) * h / np.pi).astype(int)
    for i, j in enumerate(idx):
        mask[:j, i] = 1
    mask = np.roll(np.concatenate([mask] * 4, 1), 3 * w // 8, 1)

    tp[mask] = 4
    tp[np.flip(mask, 0)] = 5

    return tp.astype(np.int32)
```

**Comment by BrianPugh** [comment]
> In cube_dict2h() in utils.py, I think the variables in the assertion should be face_k instead of k:

the `cube_dict2h` bug was fix in https://github.com/sunset1995/py360convert/commit/20c521072b7429d9858dd854be28d4705816b912 and will be included in the upcoming release (early Jan 2025).

> it uses np.bool, which doesn't seem to exist. Instead I specified the datatype as a boolean

fixed in #20 and will also be included in the upcoming release (early Jan 2025). Thanks!
