### ISSUE TITLE
error in py360convert/utils.py line no: 193

### ISSUE THREAD

**Issue by pemagrg1** [sunset1995/py360convert#3]
In py360convert/utils.py line no: 193, you have an unknown variable reference "k" commenting that line works though. 
```
def cube_dict2h(cube_dict, face_k=['F', 'R', 'B', 'L', 'U', 'D']):
    # assert len(k) == 6
    return cube_list2h([cube_dict[k] for k in face_k])
```

**Comment by sunset1995** [comment]
Fixed. Thanks!

**Comment by youngmac1106** [comment]
Met the same problem.
Fixed by your soluton. Thanks!

**Comment by BrianPugh** [comment]
the `cube_dict2h` bug was fix in https://github.com/sunset1995/py360convert/commit/20c521072b7429d9858dd854be28d4705816b912 and will be included in the upcoming release (early Jan 2025).
