### ISSUE TITLE
Numba Support

### ISSUE THREAD

**Issue by Skylion007** [sunset1995/py360convert#9]
With some rewriting to support Numba, this library could be even faster. It would require a bit of refactoring, but it might make the code even faster and unlocks the ability to use fastmath, autoparallelilzation and other features.

The jit_module function from numba gets you part of the way there, but there were several parts of the functions like c2e that needs to be rewritten into smaller functions or slightly modified to use the supported functions in numpy.

**Comment by swell-d** [comment]
That would be great

**Comment by BrianPugh** [comment]
I'm open to PRs if someone wants to take a stab at this!

**Comment by BrianPugh** [comment]
I did a first stab at this in the `numba` branch, but it didn't yield faster code. I'm not particularly well experienced in `numba`, so other eyes on this would be appreciated.

**Comment by BrianPugh** [comment]
I did a bunch of optimization in #38. It should be a little bit faster with a vanilla install, but it should now be several times faster if opencv is installed. I think this takes away a lot of the attractiveness of a numba-implementation low. Closing for now!
